export const SET_ERROR = "SET_ERROR";
export const INCREASE_ONGOING_REQUESTS = "INCREASE_ONGOING_REQUESTS";
export const SET_SEARCH_ONGOING = "SET_SEARCH_ONGOING";

export const GET_ALL_MOVIES_SUCCESS = "GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_PLANETS_SUCCESS = "GET_ALL_PLANETS_SUCCESS";
export const GET_ALL_SPECIES_SUCCESS = "GET_ALL_SPECIES_SUCCESS";

export const SEARCH_FOR_CHARACTER_SUCCESS = "SEARCH_FOR_CHARACTER_SUCCESS";
export const SEARCH_FOR_MORE_CHARACTER_SUCCESS =
  "SEARCH_FOR_MORE_CHARACTER_SUCCESS";
export const SEARCH_FOR_CHARACTER_ERROR = "SEARCH_FOR_CHARACTER_ERROR";
